import JSZip from 'jszip';
import { saveAs } from 'file-saver';
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib-with-encrypt';
import { ProcessedFile } from '@/types/payslip';

// Generate a PDF with actual content
const generatePdfContent = async (
  fileName: string, 
  employeeId: string, 
  employeeName: string,
  pageNumber: number
): Promise<Uint8Array> => {
  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([612, 792]); // Letter size
  
  const helveticaBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
  const helvetica = await pdfDoc.embedFont(StandardFonts.Helvetica);
  
  const { height } = page.getSize();
  
  // Header
  page.drawText('PAYSLIP', {
    x: 50,
    y: height - 80,
    size: 28,
    font: helveticaBold,
    color: rgb(0.2, 0.2, 0.2),
  });
  
  // Company info
  page.drawText('PaySync Generated Document', {
    x: 50,
    y: height - 110,
    size: 12,
    font: helvetica,
    color: rgb(0.4, 0.4, 0.4),
  });
  
  // Separator line
  page.drawLine({
    start: { x: 50, y: height - 130 },
    end: { x: 562, y: height - 130 },
    thickness: 1,
    color: rgb(0.8, 0.8, 0.8),
  });
  
  // Employee details section
  page.drawText('Employee Details', {
    x: 50,
    y: height - 170,
    size: 14,
    font: helveticaBold,
    color: rgb(0.2, 0.2, 0.2),
  });
  
  const details = [
    { label: 'Name:', value: employeeName },
    { label: 'Employee ID:', value: employeeId },
    { label: 'Page Number:', value: `${pageNumber}` },
    { label: 'Generated:', value: new Date().toLocaleDateString() },
    { label: 'File:', value: fileName },
  ];
  
  let yPos = height - 200;
  details.forEach(({ label, value }) => {
    page.drawText(label, {
      x: 50,
      y: yPos,
      size: 11,
      font: helveticaBold,
      color: rgb(0.3, 0.3, 0.3),
    });
    page.drawText(value, {
      x: 150,
      y: yPos,
      size: 11,
      font: helvetica,
      color: rgb(0.2, 0.2, 0.2),
    });
    yPos -= 25;
  });
  
  // Footer
  page.drawText('This is a simulated payslip generated by PaySync for demonstration purposes.', {
    x: 50,
    y: 50,
    size: 9,
    font: helvetica,
    color: rgb(0.5, 0.5, 0.5),
  });
  
  return pdfDoc.save();
};

// Generate an encrypted PDF using the employee ID as the password
const generateEncryptedPdf = async (
  fileName: string, 
  employeeId: string, 
  employeeName: string,
  pageNumber: number
): Promise<Uint8Array> => {
  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([612, 792]);
  
  const helveticaBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
  const helvetica = await pdfDoc.embedFont(StandardFonts.Helvetica);
  
  const { height } = page.getSize();
  
  // Header with encryption indicator
  page.drawText('PAYSLIP', {
    x: 50,
    y: height - 80,
    size: 28,
    font: helveticaBold,
    color: rgb(0.1, 0.4, 0.2),
  });
  
  page.drawText('Password Protected Document', {
    x: 50,
    y: height - 110,
    size: 12,
    font: helvetica,
    color: rgb(0.3, 0.5, 0.3),
  });
  
  page.drawText('PaySync Generated Document', {
    x: 50,
    y: height - 130,
    size: 10,
    font: helvetica,
    color: rgb(0.4, 0.4, 0.4),
  });
  
  // Separator line
  page.drawLine({
    start: { x: 50, y: height - 150 },
    end: { x: 562, y: height - 150 },
    thickness: 1,
    color: rgb(0.8, 0.8, 0.8),
  });
  
  // Employee details section
  page.drawText('Employee Details', {
    x: 50,
    y: height - 190,
    size: 14,
    font: helveticaBold,
    color: rgb(0.2, 0.2, 0.2),
  });
  
  const details = [
    { label: 'Name:', value: employeeName },
    { label: 'Employee ID:', value: employeeId },
    { label: 'Page Number:', value: `${pageNumber}` },
    { label: 'Generated:', value: new Date().toLocaleDateString() },
    { label: 'File:', value: fileName },
  ];
  
  let yPos = height - 220;
  details.forEach(({ label, value }) => {
    page.drawText(label, {
      x: 50,
      y: yPos,
      size: 11,
      font: helveticaBold,
      color: rgb(0.3, 0.3, 0.3),
    });
    page.drawText(value, {
      x: 150,
      y: yPos,
      size: 11,
      font: helvetica,
      color: rgb(0.2, 0.2, 0.2),
    });
    yPos -= 25;
  });
  
  // Footer
  page.drawText('This payslip is password-protected. Contact HR if you cannot access it.', {
    x: 50,
    y: 50,
    size: 9,
    font: helvetica,
    color: rgb(0.5, 0.5, 0.5),
  });
  
  // ACTUAL PDF ENCRYPTION using the employee ID as the password
  // The userPassword is what the employee enters to open the PDF
  // The ownerPassword is for admin access (using a fixed value)
  pdfDoc.encrypt({
    userPassword: employeeId,
    ownerPassword: 'PaySyncAdmin2024',
    permissions: {
      printing: 'highResolution',
      modifying: false,
      copying: false,
      annotating: false,
      fillingForms: true,
      contentAccessibility: true,
      documentAssembly: false,
    },
  });
  
  return pdfDoc.save();
};

export const downloadSingleFile = async (file: ProcessedFile, isEncrypted: boolean = false): Promise<void> => {
  const pdfBytes = isEncrypted 
    ? await generateEncryptedPdf(file.fileName, file.employeeId, file.employeeName, file.pageNumber)
    : await generatePdfContent(file.fileName, file.employeeId, file.employeeName, file.pageNumber);
  
  const blob = new Blob([new Uint8Array(pdfBytes)], { type: 'application/pdf' });
  saveAs(blob, file.fileName);
};

export const downloadAllAsZip = async (
  files: ProcessedFile[], 
  isEncrypted: boolean = false,
  zipFileName: string = 'payslips.zip'
): Promise<void> => {
  const zip = new JSZip();

  // Generate all PDFs in parallel
  const pdfPromises = files.map(async (file) => {
    const pdfBytes = isEncrypted 
      ? await generateEncryptedPdf(file.fileName, file.employeeId, file.employeeName, file.pageNumber)
      : await generatePdfContent(file.fileName, file.employeeId, file.employeeName, file.pageNumber);
    return { fileName: file.fileName, pdfBytes };
  });

  const pdfs = await Promise.all(pdfPromises);
  
  pdfs.forEach(({ fileName, pdfBytes }) => {
    zip.file(fileName, pdfBytes);
  });

  const content = await zip.generateAsync({ type: 'blob' });
  saveAs(content, zipFileName);
};
